# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: emily c. ritter
email: emily.c.ritter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  thank you for visiting www.emilycritter.com<br>
  &copy; Emily C. Ritter
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: emilycritter
github_username:  emilycritter

# Build settings
markdown: kramdown
permalink: /blog/:year/:title
